services:
  postgres:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASS}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/${DBNAME}
      - SPRING_DATASOURCE_USERNAME=${DBUSER}
      - SPRING_DATASOURCE_PASSWORD=${DBPASS}
    ports:
      - '80:80'

