version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASS}
      - POSTGRES_DB=lbdb
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # This mounts the Docker socket from the host
    environment:
      - SPRING_DATASOURCE_USERNAME=${DBUSER}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/lbdb
      - SPRING_DATASOURCE_PASSWORD=${DBPASS}
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - '80:80'

