services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${dbname}'
      - 'POSTGRES_PASSWORD=${dbpass}'
      - 'POSTGRES_USER=${dbuser}'
    ports:
      - '5432:5432'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '80:80'

