services:
  postgres:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASS}
      POSTGRES_DB: lbdb
    volumes:
      - pg_data:/var/lib/postgresql/data  # Persist data in this volume

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_USERNAME: ${DBUSER}
      SPRING_DATASOURCE_PASSWORD: ${DBPASS}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lbdb
      DOCKER_HOST: unix:///var/run/docker.sock
    ports:
      - '80:80'

volumes:
  pg_data: