auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_transfer_retries: 0

schema_config:
  configs:
    - from: 2023-10-01  # Date from when this config is valid
      store: boltdb-shipper  # Type of store for logs
      object_store: filesystem  # Where to store logs (filesystem)
      schema: v11  # Schema version (use latest)
      index:
        prefix: index_  # Prefix for index files
        period: 168h  # How often to rotate index files (1 week)

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/boltdb-cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks  # Directory for log chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h  # Reject logs older than 7 days

chunk_store_config:
  max_look_back_period: 0s  # No limit on look-back period for queries

table_manager:
  retention_deletes_enabled: true  # Enable log retention
  retention_period: 168h  # Retain logs for 7 days
