jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged # Required for Docker-in-Docker (DinD)
        ports:
          - 2375:2375
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Add known hosts
        run: |
          mkdir -p -m 0700 ~/.ssh
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            set -e
            export DBUSER=${{ secrets.DBUSER }}
            export DBPASS=${{ secrets.DBPASS }}
            export DBNAME=jdbc:postgresql://postgres:5432/lbdb
            cd igw/lb
            git pull
            docker compose down
            docker compose up -d --build
          EOF
